[db]
host = "sql12.freesqldatabase.com"
user = "sql12783209"
pass = "4IV7v8wX8e"
name = "sql12783209"

[email]
address = "vinodwij.hayleys.digitalt@gmail.com"
password = "bmgi atsy kliy kbvs"

[llm]
api_url = "https://api.openai.com/v1/chat/completions"
model = "gpt-4o"
api_key = "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"
